routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middlewareGroups' => ['web']], function(){
    // Authentication Routes
    Route::get('login', ['as' => 'auth.login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'auth.login', 'uses' => 'Auth\LoginController@login']);
    Route::get('logoff', ['as' => 'auth.logoff', 'uses' => 'Auth\LoginController@logout']);

    // Register Routes
    //Route::get('auth/register', ['as' => 'auth.register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
    //Route::post('auth/register', ['as' => 'auth.register', 'uses' => 'Auth\RegisterController@register']);


    // Social Resources
    Route::resource('social', 'SocialController',['except' => ['create', 'show']]);
    // Datos Resources
    Route::resource('datos', 'DatosController',['except' => ['create', 'show']]);
    // Hobbies Resources
    Route::resource('hobbies', 'HobbiesController',['except' => ['create', 'show']]);
    // Jobs Resources
    Route::resource('jobs', 'JobsController',['except' => ['create', 'show']]);
    // Jobs Resources
    Route::resource('grades', 'GradesController',['except' => ['create', 'show']]);
    // Skills Resources
    Route::resource('skills', 'SkillsController',['except' => ['create', 'show']]);
  
    // Inici routes
    Route::get('/', ['as' => 'inicio', 'uses' => 'PagesController@getIndex']);
    Route::post('/', ['as' => 'inicio', 'uses' => 'PagesController@sendContact']);
});

resources/views/_statics/_globalJS.blade.php
<!-- Scripts -->
<script type="text/javascript" charset="utf-8" src="http://cdn.dxcodercrew.net/jQuery/1.12.3/jquery.min.js"> </script>
<script type="text/javascript" charset="utf-8" src="http://cdn.dxcodercrew.net/material-design-lite/material.min.js"></script>
<script type="text/javascript" charset="utf-8" src="http://cdn.dxcodercrew.net/material-modal/dist/js/material-modal.min.js"></script>
<script type="text/javascript" charset="utf-8" src="http://cdn.dxcodercrew.net/trumbowyg/dist/trumbowyg.min.js"></script>
<script type="text/javascript" charset="utf-8" src="http://cdn.dxcodercrew.net/trumbowyg/dist/langs/es.min.js"></script>
<script type="text/javascript">

$(function(){
  /**
   * Configuracion del editor WYSIWYG
   */
  var textConfig = {
    lang: 'es',
    btns: [
        ['viewHTML'],
        ['undo', 'redo'], // Only supported in Blink browsers
        ['formatting'],
        ['strong', 'em', 'del'],
        ['superscript', 'subscript'],
        ['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
        ['unorderedList', 'orderedList'],
        ['removeformat']
    ],
    autogrow: true
  };
  
  $("#text-editor").trumbowyg(textConfig);
});
</script>

resources/views/_statics/_header.blade.php
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>Raul Guerrero | CV @yield('title')</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">

    <!--link rel="stylesheet" href="http://cdn.dxcodercrew.net/materialize/dist/css/materialize.min.css"-->
    <link rel="stylesheet" href="http://cdn.dxcodercrew.net/material-design-lite/material.min.css" />
    <link rel="stylesheet" href="http://cdn.dxcodercrew.net/material-design-lite/material-teal-green.min.css" />
    <link rel="stylesheet" href="http://cdn.dxcodercrew.net/material-modal/dist/css/material-modal.min.css" />
    <link rel="stylesheet" href="http://cdn.dxcodercrew.net/trumbowyg/dist/ui/trumbowyg.min.css">
    <link rel='stylesheet' href='http://cdn.dxcodercrew.net/font-awesome/4.7.0/css/font-awesome.css' />
    <link rel='stylesheet' href='http://cdn.dxcodercrew.net/fontello/css/fontello.css' />
    <!-- Estilos propios -->
    {{ Html::style('css/styles.css') }}
    {{ Html::style('css/social-icons.css') }}
    {{ Html::style('css/mdl-custom.css') }}
    @yield('stylesheets')
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

resources/views/_statics/_messages.blade.php
@if(Session::has('success'))
<dialog class="mdl-dialog  mdl-color--teal top-spacing-50">
  <h4 class="mdl-dialog__title"></h4>
  <div class="mdl-dialog__content mdl-color-text--white">
    <p>
      {{ Session::get('success') }}
    </p>
  </div>
  <div class="mdl-dialog__actions">
    <button type="button" class="mdl-button close">Cerrar</button>
  </div>
</dialog>
@elseif(Session::has('error'))
<dialog class="mdl-dialog  mdl-color--red top-spacing-50">
  <h4 class="mdl-dialog__title"></h4>
  <div class="mdl-dialog__content mdl-color-text--white">
    <p>
      {{ Session::get('error') }}
    </p>
  </div>
  <div class="mdl-dialog__actions">
    <button type="button" class="mdl-button close">Cerrar</button>
  </div>
</dialog>
@endif

@if(count($errors) > 0)
<dialog class="mdl-dialog  mdl-color--red top-spacing-50">
  <h4 class="mdl-dialog__title">Errores:</h4>
  <div class="mdl-dialog__content mdl-color-text--white">
    <ul>
      @foreach ($errors->all() as $error)
      <li>{{ $error }}</li>
      @endforeach
    </ul>
  </div>
  <div class="mdl-dialog__actions">
    <button type="button" class="mdl-button close">Cerrar</button>
  </div>
</dialog>
@endif

@section('scripts')
<script>
  var dialog = document.querySelector('dialog');
  
  if(dialog != null){
    if (! dialog.showModal) {
      dialogPolyfill.registerDialog(dialog);
    }

    dialog.showModal();

    dialog.querySelector('.close').addEventListener('click', function() {
      dialog.close();
    });
  }
</script>
@endsection

resources/views/_statics/_nav.blade.php
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title">
        CV | Raul Guerrero
      </span>
      <div class="mdl-layout-spacer"></div>
      @if(Auth::check())
        <button id="demo-menu-lower-right"
                class="mdl-button mdl-js-button mdl-button--icon">
          <i class="material-icons">more_vert</i>
        </button>
        <nav class="mdl-navigation">
          <a href="{{ route('auth.logoff') }}" class="mdl-navigation__link">
            <i class="material-icons">power_settings_new</i>
          </a>
        </nav>
        <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect"
            for="demo-menu-lower-right">
          <li class="mdl-menu__item"><a href="{{ route('datos.index') }}" class="mdl-navigation__link mdl-button--colored">Datos</a></li>
          <li class="mdl-menu__item"><a href="{{ route('social.index') }}" class="mdl-navigation__link">Social</a></li>
          <li class="mdl-menu__item"><a href="{{ route('hobbies.index') }}" class="mdl-navigation__link">Hobbies</a></li>
          <li class="mdl-menu__item"><a href="{{ route('jobs.index') }}" class="mdl-navigation__link">Trabajos</a></li>
          <li class="mdl-menu__item"><a href="{{ route('grades.index') }}" class="mdl-navigation__link">Estudios</a></li>
          <li class="mdl-menu__item"><a href="{{ route('skills.index') }}" class="mdl-navigation__link">Habilidades</a></li>
        </ul>
      @else
        <nav class="mdl-navigation">
          <a href="{{ route('auth.login') }}" class="mdl-navigation__link">Acceder</a>
        </nav>
      @endif
    </div>
  </header>