routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middlewareGroups' => ['web']], function(){
    // Authentication Routes
    Route::get('login', ['as' => 'auth.login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'auth.login', 'uses' => 'Auth\LoginController@login']);
    Route::get('logoff', ['as' => 'auth.logoff', 'uses' => 'Auth\LoginController@logout']);

    // Register Routes
    //Route::get('auth/register', ['as' => 'auth.register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
    //Route::post('auth/register', ['as' => 'auth.register', 'uses' => 'Auth\RegisterController@register']);


    // Social Resources
    Route::resource('social', 'SocialController',['except' => ['create', 'show']]);
    // Datos Resources
    Route::resource('datos', 'DatosController',['except' => ['create', 'show']]);
    // Hobbies Resources
    Route::resource('hobbies', 'HobbiesController',['except' => ['create', 'show']]);
    // Jobs Resources
    Route::resource('jobs', 'JobsController',['except' => ['create', 'show']]);
    // Jobs Resources
    Route::resource('grades', 'GradesController',['except' => ['create', 'show']]);
    // Skills Resources
    Route::resource('skills', 'SkillsController',['except' => ['create', 'show']]);
  
    // Inici routes
    Route::get('/', ['as' => 'inicio', 'uses' => 'PagesController@getIndex']);
    Route::post('/', ['as' => 'inicio', 'uses' => 'PagesController@sendContact']);
});

app/Grade.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Grade extends Model
{
    /**
     * Configuracion para eliminar el autoincremental por el uso de UUIDs
     */
    protected $primaryKey = "id";
    public $incrementing = false;
}

app/Http/Controllers/GradesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Webpatser\Uuid\Uuid;
use App\Grade;
use Session;

class GradesController extends Controller
{
    /**
     * Permite el acceso a los usuarios que pertenezcan al middleware auth
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $grades = Grade::orderBy('fecha_inicio', 'desc')->get();
        return view('grades.index')->withGrades($grades);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Not in use
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
          'titulo' => 'required',
          'colegio' => 'required',
          'fecha_inicio' => 'required'
        ]);
      
        $grade = new Grade;
        
        $grade->id = Uuid::generate();
        $grade->titulo = $request->titulo;
        $grade->colegio = $request->colegio;
        $grade->fecha_inicio = $request->fecha_inicio;
        $grade->fecha_fin = $request->fecha_fin;
        $grade->descripcion = $request->descripcion;
      
        $grade->save();
        Session::flash('success', 'Estudios guardado');

        return redirect()->route('grades.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // Not in use
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $grade = Grade::find($id);
        return view('grades/edit')
          ->withGrade($grade);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
          'titulo' => 'required',
          'colegio' => 'required',
          'fecha_inicio' => 'required'
        ]);
      
        $grade = Grade::find($id);
        
        $grade->titulo = $request->titulo;
        $grade->colegio = $request->colegio;
        $grade->fecha_inicio = $request->fecha_inicio;
        $grade->fecha_fin = $request->fecha_fin;
        $grade->descripcion = $request->descripcion;
      
        $grade->save();
        Session::flash('success', 'Estudios guardado');

        return redirect()->route('grades.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $grade = Grade::find($id);
      if($grade->delete()){
        Session::flash('success', 'Dato eliminado correctamente');
      }else{
        Session::flash('error', 'Dato no eliminado');
      }
      return redirect()->route('grades.index');
    }
}

resources/views/grades/create.blade.php
{!! Form::open(['route' => 'grades.store']) !!}
<div class="modal__content">
  <div class="modal__header">
    <div class="modal__title">
      <h2 class="modal__title-text">Nuevo estudio</h2>
    </div>
    <span class="mdl-button mdl-button--icon mdl-js-button material-icons modal__close"></span>
  </div>
  <div class="modal__text mdl-cell mdl-cell--12-col">
    <div class="mdl-cell--5-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      {{ Form::text('titulo',null, ['class' => 'mdl-textfield__input']) }}
      {{ Form::label('titulo','Titulo', ['class' => 'mdl-textfield__label']) }}
    </div>
    <div class="mdl-cell--5-col mdl-cell--1-offset mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        {{ Form::text('colegio',null, ['class' => 'mdl-textfield__input']) }}
        {{ Form::label('colegio','Colegio', ['class' => 'mdl-textfield__label']) }}
    </div>
    <div class="mdl-cell--5-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      {{ Form::date('fecha_inicio',null, ['class' => 'mdl-textfield__input']) }}
      {{ Form::label('fecha_inicio','Fecha Inicio', ['class' => 'mdl-textfield__label']) }}
    </div>
    <div class="mdl-cell--5-col mdl-cell--1-offset mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      {{ Form::date('fecha_fin',null, ['class' => 'mdl-textfield__input']) }}
      {{ Form::label('fecha_fin','Fecha fin', ['class' => 'mdl-textfield__label']) }}
    </div>
    <div class="mdl-cell--12-col">
      {{ Form::textarea('descripcion',null, ['id' => 'text-editor']) }}
    </div>
  </div>
  <div class="modal__footer">
    <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Guardar</button>
  </div>
</div>
{!! Form::close() !!}

resources/views/grades/edit.blade.php
@extends('back')

@section('content')
<div class="mdl-cell mdl-cell--6-col mdl-cell--12-phone mdl-cell--3-offset-desktop top-spacing-50">
  <div class="mdl-card mdl-shadow--3dp mdl-cell--12-col mdl-cell--10-phone">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">Estudio</h2>
    </div>
    <div class="mdl-card__supporting-text mdl-cell--12-phone">
    {{ Form::model($grade,['route' => ['grades.update', $grade->id], 'files' => 'false', 'method' => 'PUT']) }}
      <div class="mdl-cell--5-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        {{ Form::text('titulo',null, ['class' => 'mdl-textfield__input']) }}
        {{ Form::label('titulo','Titulo', ['class' => 'mdl-textfield__label']) }}
      </div>
      <div class="mdl-cell--5-col mdl-cell--1-offset mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          {{ Form::text('colegio',null, ['class' => 'mdl-textfield__input']) }}
          {{ Form::label('colegio','Colegio', ['class' => 'mdl-textfield__label']) }}
      </div>
      <div class="mdl-cell--5-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        {{ Form::date('fecha_inicio',null, ['class' => 'mdl-textfield__input']) }}
        {{ Form::label('fecha_inicio','Fecha Inicio', ['class' => 'mdl-textfield__label']) }}
      </div>
      <div class="mdl-cell--5-col mdl-cell--1-offset mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        {{ Form::date('fecha_fin',null, ['class' => 'mdl-textfield__input']) }}
        {{ Form::label('fecha_fin','Fecha fin', ['class' => 'mdl-textfield__label']) }}
      </div>
      <div class="mdl-cell--12-col">
        {{ Form::textarea('descripcion',null, ['id' => 'text-editor']) }}
      </div>
    <div class="card-footer">
      <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Actualizar</button>
    </div>
    {{ Form::close() }}
    </div>
    <div class="mdl-card__menu">
      <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect modal__trigger" data-modal="#modalDelEstudio">
        <i class="material-icons">delete</i>
      </button>
    </div>
  </div>
</div>
<!-- Modal Structure -->
<div id="modalDelEstudio" class="modal modal__bg">
  <div class="modal__dialog">
    <div class="modal__content">
      {!! Form::open(['route' => ['grades.destroy', $grade->id], 'method' => 'DELETE']) !!}
      <div class="modal__header">
        <div class="modal__title">
          <h2 class="modal__title-text">Borrar Estudio</h2>
        </div>
        <span class="mdl-button mdl-button--icon mdl-js-button material-icons modal__close"></span>
      </div>
      <div class="modal__text">
        <p>
          Deseas eliminar el estudio?
        </p>
        <p>
          <sub>Se eliminará para siempre y no se podra recuperar</sub>
        </p>
      </div>
      <div class="modal__footer">
        <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Borrar</button>
      </div>
      {!! Form::close() !!}
    </div>
  </div>
</div>
@endsection

resources/views/grades/index.blade.php
@extends('back')

@section('content')
<div class="mdl-cell mdl-cell--6-col mdl-cell--12-phone mdl-cell--3-offset-desktop top-spacing-50">
  <div class="mdl-card mdl-shadow--0dp mdl-cell--12-col mdl-cell--10-phone">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">Estudios</h2>
    </div>
    <div class="mdl-card__supporting-text mdl-cell--12-phone">
      @foreach($grades as $i => $grade)
        @if($i != 0)
          <hr>
        @endif
        <div class="mdl-card mdl-shadow--0dp mdl-cell--12-col mdl-cell--10-phone">
          <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">{{ $grade->colegio }}</h2>
          </div>
          <div class="mdl-card__supporting-text mdl-cell--12-phone">
            <p>{{ $grade->titulo }}</p>
          </div>
          <div class="mdl-card__actions">
            <a class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect modal__trigger" data-modal="#modal{{$grade->id}}">+ info</a>
            <a href="{{ route('grades.edit', $grade->id) }}" class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect">Editar</a>
          </div>
        </div>
      @endforeach
    </div>
    <div class="mdl-card__menu">
      <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect modal__trigger" data-modal="#modalNewGrade">
        <i class="material-icons">add</i>
      </button>
    </div>
  </div>
  <!-- Modal Structure -->
  <div id="modalNewGrade" class="modal modal__bg">
    <div class="modal__dialog">
      @include('grades/create')
    </div>
  </div>
</div>
@foreach($grades as $i => $grade)
<!-- Modal Structure -->
<div id="modal{{$grade->id}}" class="modal modal__bg">
  <div class="modal__dialog">
    <div class="modal__content">
      <div class="modal__header">
        <div class="modal__title">
          <h2 class="modal__title-text">{{ $grade->colegio }}</h2>
        </div>
        <span class="mdl-button mdl-button--icon mdl-js-button material-icons modal__close"></span>
      </div>
      <div class="modal__text">
         {!! $grade->descripcion !!}
      </div>
      <div class="modal__footer">
        <a class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored modal__close">Cerrar</a>
      </div>
    </div>
  </div>
</div>
@endforeach
@endsection