routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['middlewareGroups' => ['web']], function(){
    // Authentication Routes
    Route::get('login', ['as' => 'auth.login', 'uses' => 'Auth\LoginController@showLoginForm']);
    Route::post('login', ['as' => 'auth.login', 'uses' => 'Auth\LoginController@login']);
    Route::get('logoff', ['as' => 'auth.logoff', 'uses' => 'Auth\LoginController@logout']);

    // Register Routes
    //Route::get('auth/register', ['as' => 'auth.register', 'uses' => 'Auth\RegisterController@showRegistrationForm']);
    //Route::post('auth/register', ['as' => 'auth.register', 'uses' => 'Auth\RegisterController@register']);


    // Social Resources
    Route::resource('social', 'SocialController',['except' => ['create', 'show']]);
    // Datos Resources
    Route::resource('datos', 'DatosController',['except' => ['create', 'show']]);
    // Hobbies Resources
    Route::resource('hobbies', 'HobbiesController',['except' => ['create', 'show']]);
    // Jobs Resources
    Route::resource('jobs', 'JobsController',['except' => ['create', 'show']]);
    // Jobs Resources
    Route::resource('grades', 'GradesController',['except' => ['create', 'show']]);
    // Skills Resources
    Route::resource('skills', 'SkillsController',['except' => ['create', 'show']]);
  
    // Inici routes
    Route::get('/', ['as' => 'inicio', 'uses' => 'PagesController@getIndex']);
    Route::post('/', ['as' => 'inicio', 'uses' => 'PagesController@sendContact']);
});

resources/views/rrss/create.blade.php
{!! Form::open(['route' => 'social.store']) !!}
<div class="modal__content">
  <div class="modal__header">
    <div class="modal__title">
      <h2 class="modal__title-text">Nueva Red Social</h2>
    </div>
    <span class="mdl-button mdl-button--icon mdl-js-button material-icons modal__close"></span>
  </div>
  <div class="modal__text">
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      {{ Form::text('rrss',null, ['class' => 'mdl-textfield__input']) }}
      {{ Form::label('rrss','Red Social', ['class' => 'mdl-textfield__label']) }}
    </div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      {{ Form::text('url',null, ['class' => 'mdl-textfield__input']) }}
      {{ Form::label('url','URL', ['class' => 'mdl-textfield__label']) }}
    </div>
  </div>
  <div class="modal__footer">
    <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Guardar</button>
  </div>
</div>
{!! Form::close() !!}

resources/views/rrss/edit.blade.php
@extends('back')

@section('content')
<div class="mdl-cell mdl-cell--4-col mdl-cell--12-phone mdl-cell--4-offset-desktop top-spacing-50">
  <div class="mdl-card mdl-shadow--3dp mdl-cell--12-col mdl-cell--10-phone">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">Datos</h2>
    </div>
    <div class="mdl-card__supporting-text mdl-cell--12-phone">
    {{ Form::model($rs,['route' => ['social.update', $rs->id], 'files' => 'false', 'method' => 'PUT']) }}
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        {{ Form::text('rrss',null, ['class' => 'mdl-textfield__input']) }}
        {{ Form::label('rrss','Red Social', ['class' => 'mdl-textfield__label']) }}
      </div>
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
        {{ Form::text('url',null, ['class' => 'mdl-textfield__input']) }}
        {{ Form::label('url','URL', ['class' => 'mdl-textfield__label']) }}
      </div>
    <div class="card-footer">
      <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Actualizar</button>
    </div>
    {{ Form::close() }}
    </div>
    <div class="mdl-card__menu">
      <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect modal__trigger" data-modal="#modalDelSocial">
        <i class="material-icons">delete</i>
      </button>
    </div>
  </div>
</div>
<!-- Modal Structure -->
<div id="modalDelSocial" class="modal modal__bg">
  <div class="modal__dialog">
    <div class="modal__content">
      {!! Form::open(['route' => ['social.destroy', $rs->id], 'method' => 'DELETE']) !!}
      <div class="modal__header">
        <div class="modal__title">
          <h2 class="modal__title-text">Borrar Red social</h2>
        </div>
        <span class="mdl-button mdl-button--icon mdl-js-button material-icons modal__close"></span>
      </div>
      <div class="modal__text">
        <p>
          Deseas eliminar la red social?
        </p>
        <p>
          <sub>Se eliminará para siempre y no se podra recuperar</sub>
        </p>
      </div>
      <div class="modal__footer">
        <button type="submit" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">Borrar</button>
      </div>
      {!! Form::close() !!}
    </div>
  </div>
</div>
@endsection

resources/views/rrss/index.blade.php
@extends('back')

@section('content')
<div class="mdl-cell mdl-cell--6-col mdl-cell--12-phone mdl-cell--3-offset-desktop top-spacing-50">
  <div class="mdl-card mdl-shadow--0dp mdl-cell--12-col mdl-cell--10-phone">
    <div class="mdl-card__title">
      <h2 class="mdl-card__title-text">Redes Sociales</h2>
    </div>
    <div class="mdl-card__supporting-text mdl-cell--12-phone">
      <table class="mdl-data-table mdl-js-data-table mdl-cell--12-col">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Pagina</th>
                <th>Editar</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($rrss as $i => $rs)
                <tr>
                    <td style="text-transform: capitalize">{{ $rs->rrss }}</td>
                    <td>
                      <a href="{{ $rs->url }}"><i class="material-icons">link</i></a>
                    </td>
                    <td><a href="{{ route('social.edit', $rs->id) }}" ><i class="fa fa-pencil fa-lg mdl-color-text--black"></i></a></td>
                </tr>
            @endforeach
        </tbody>
      </table>
    </div>
    <div class="mdl-card__menu">
      <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect modal__trigger" data-modal="#modalNewDato">
        <i class="material-icons">add</i>
      </button>
    </div>
  </div>
  <!-- Modal Structure -->
  <div id="modalNewDato" class="modal modal__bg">
    <div class="modal__dialog">
      @include('rrss/create')
    </div>
  </div>
</div>
@endsection